{{- if .Values.secret.create }}
apiVersion: v1
{{- with .Values.secret.data }}
data:
  {{- toYaml . | nindent 4 }}
{{- end }}
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.NameSpace }}
type: Opaque
{{- end }}