apiVersion: v1
kind: Service
metadata:
  name:  "{{ .Values.prefix }}-{{ .Values.appName }}-service"
  namespace: {{ .Values.NameSpace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app:  "{{ .Values.prefix }}-{{ .Values.appName }}"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
